import { useState, type FormEvent } from "react";
import { Link, Navigate, useSearchParams } from "react-router-dom";
import { useAuth } from "../state/auth";

export function Auth() {
  const [params] = useSearchParams(); const { user, login, register } = useAuth();
  const [mode, setMode] = useState(params.get("mode") === "register" ? "register" : "login");
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  if (user) return <Navigate to="/app" replace />;
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { mode === "register" ? await register(name, email, password) : await login(email, password); } catch (error) { setError(error instanceof Error ? error.message : "Could not continue."); } finally { setBusy(false); } }
  return <div className="auth-page"><Link className="wordmark auth-page__brand" to="/"><span>V</span> VYIRAL</Link><div className="auth-art"><div className="auth-art__copy"><span>CAREER INTELLIGENCE</span><h1>Build a story<br/>worth <em>remembering.</em></h1><p>Thoughtful tools. Exceptional presentation. Your work, articulated with clarity.</p></div><div className="auth-orb"/></div><main className="auth-panel"><div className="auth-panel__inner"><span className="kicker">THE VYIRAL STUDIO</span><h2>{mode === "register" ? "Create your account" : "Welcome back"}</h2><p>{mode === "register" ? "Start crafting your next opportunity." : "Continue building your career story."}</p><form onSubmit={submit}>{mode === "register" && <label>FULL NAME<input autoComplete="name" value={name} onChange={e => setName(e.target.value)} placeholder="Alex Morgan" required minLength={2}/></label>}<label>EMAIL ADDRESS<input type="email" autoComplete="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="you@example.com" required/></label><label>PASSWORD<input type="password" autoComplete={mode === "register" ? "new-password" : "current-password"} value={password} onChange={e => setPassword(e.target.value)} placeholder={mode === "register" ? "At least 10 characters" : "Your password"} required minLength={mode === "register" ? 10 : 1}/></label>{error && <div className="auth-error" role="alert">{error}</div>}<button disabled={busy}>{busy ? "PLEASE WAIT…" : mode === "register" ? "CREATE ACCOUNT  →" : "ENTER THE STUDIO  →"}</button></form><div className="auth-switch">{mode === "register" ? "Already have an account?" : "New to Vyiral?"} <button onClick={() => { setMode(mode === "register" ? "login" : "register"); setError(""); }}>{mode === "register" ? "Sign in" : "Create an account"}</button></div><small>By continuing, you agree to our Terms and Privacy Policy.</small></div></main></div>;
}
